# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Yu
tagline:             '''s blog'
description:         'Yu''s blog'
baseurl:             ''

# Plugins
gems:                [jekyll-paginate]
paginate:            5

# Conversion
# excerpt_separator:   "\n\n" # You can explicitly override this by setting a value in the YAML fromt matter of a certain post