# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Yu
tagline:             '''s blog'
description:         'Yu''s blog'
baseurl:             ''
paginate:            5
gems:                [jekyll-paginate]

# Excerpt